// Package export converts yori artifacts into other tools' formats. Today it
// targets promptfoo: yori owns authoring/composition/versioning/deployment, and
// promptfoo does the model-graded evaluation.
package export

import (
	"fmt"
	"strings"

	"github.com/arjia-labs/yori/internal/render"
	"github.com/arjia-labs/yori/internal/store"
	"gopkg.in/yaml.v3"
)

// Case is one promptfoo test case ({vars, assert, description, ...}). It is
// passed through nearly verbatim, so authoring a yori cases file is the same as
// authoring promptfoo tests.
type Case = map[string]any

// pfConfig is the subset of promptfooconfig.yaml that yori generates.
type pfConfig struct {
	Description string   `yaml:"description,omitempty"`
	Prompts     []string `yaml:"prompts"`
	Providers   []string `yaml:"providers"`
	Tests       []Case   `yaml:"tests,omitempty"`
}

// Promptfoo renders an artifact with its composition resolved but variables
// left as {{ name }} placeholders, and emits a promptfooconfig.yaml. cases are
// the artifact's test cases (may be nil); providers are promptfoo provider
// strings.
func Promptfoo(rs render.Resolver, art *store.Artifact, cases []Case, providers []string) ([]byte, error) {
	// Bind every known variable to its own placeholder so composition
	// (includes/slots/extends) resolves while {{ var }} survives for promptfoo.
	vars := map[string]any{}
	for name := range art.Vars {
		vars[name] = passthrough(name)
	}
	for _, c := range cases {
		if cv, ok := c["vars"].(map[string]any); ok {
			for k := range cv {
				vars[k] = passthrough(k)
			}
		}
	}

	body, err := render.Render(art, rs, render.Options{
		Vars:     vars,
		Input:    passthrough("input"),
		NoAppend: true,
	})
	if err != nil {
		return nil, err
	}

	cfg := pfConfig{
		Description: art.Description,
		Prompts:     []string{body},
		Providers:   providers,
		Tests:       cases,
	}
	out, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, err
	}
	header := fmt.Sprintf("# Generated by yori from %s:%s\n# Review providers, then run: promptfoo eval\n", art.Type, art.Name)
	return append([]byte(header), out...), nil
}

func passthrough(name string) string { return "{{ " + name + " }}" }

// GuessProvider maps a yori `model:` hint to a promptfoo provider string.
func GuessProvider(model string) string {
	switch m := strings.ToLower(model); {
	case strings.HasPrefix(m, "claude"):
		return "anthropic:" + model
	case strings.HasPrefix(m, "gpt"), strings.HasPrefix(m, "o1"), strings.HasPrefix(m, "o3"), strings.HasPrefix(m, "o4"):
		return "openai:" + model
	default:
		return model
	}
}
